import { buildCourseOutlinePrompt } from "@/lib/ai/prompts/course-outline";
import {
  courseOutlineSchema,
  type CourseGenerationInput,
  type CourseGenerationSection,
  type CourseOutline,
  type SourceReference,
} from "@/lib/ai/schemas/course";
import type { AIProvider } from "@/lib/ai/providers/types";

function toReference(section: CourseGenerationSection): SourceReference {
  return {
    sectionId: section.id,
    sectionTitle: section.sectionTitle,
    sectionNumber: section.sectionNumber,
    pageStart: section.pageStart,
    pageEnd: section.pageEnd,
  };
}

function firstSentence(text: string, fallback: string): string {
  const cleaned = text.replace(/\s+/g, " ").trim();
  if (!cleaned) return fallback;
  const match = cleaned.match(/^(.{20,220}?[.!?])\s/);
  if (match) return match[1];
  return cleaned.slice(0, 220);
}

function chunkSections(
  sections: CourseGenerationSection[],
  moduleCount: number,
): CourseGenerationSection[][] {
  const count = Math.max(1, Math.min(moduleCount, sections.length));
  const groups: CourseGenerationSection[][] = Array.from(
    { length: count },
    () => [],
  );

  sections.forEach((section, index) => {
    groups[index % count].push(section);
  });

  return groups.filter((group) => group.length > 0);
}

/**
 * Deterministic mock generator.
 * Grounds titles/summaries in selected section text and always attaches references.
 */
export class MockAIProvider implements AIProvider {
  async generateCourseOutline(
    input: CourseGenerationInput,
  ): Promise<CourseOutline> {
    // Keep prompt construction in the path so future providers share it.
    void buildCourseOutlinePrompt(input);

    if (input.sections.length === 0) {
      throw new Error("Select at least one source section before generating.");
    }

    const groups = chunkSections(input.sections, input.moduleCount);
    const allRefs = input.sections.map(toReference);
    const primary = input.sections[0];

    const modules = groups.map((group, moduleIndex) => {
      const moduleRefs = group.map(toReference);
      const lead = group[0];
      const support = group.slice(1);

      const lessons = [
        {
          title: `Understand: ${lead.sectionTitle}`,
          summary: firstSentence(
            lead.extractedText,
            `Review the source material in ${lead.sectionTitle}.`,
          ),
          learningObjectives: [
            `Explain the key idea from ${lead.sectionTitle}.`,
            `Identify how this idea serves ${input.targetAudience}.`,
          ],
          sourceReferences: [toReference(lead)],
        },
        ...support.slice(0, 2).map((section) => ({
          title: `Apply: ${section.sectionTitle}`,
          summary: firstSentence(
            section.extractedText,
            `Apply teaching points from ${section.sectionTitle}.`,
          ),
          learningObjectives: [
            `Apply one practical takeaway from ${section.sectionTitle}.`,
          ],
          sourceReferences: [toReference(section)],
        })),
      ];

      return {
        title: `Module ${moduleIndex + 1}: ${lead.sectionTitle}`,
        description: firstSentence(
          lead.extractedText,
          `This module is grounded in ${lead.sectionTitle}.`,
        ),
        lessons,
        sourceReferences: moduleRefs,
      };
    });

    const learningOutcomes = [
      `Describe the core message drawn from ${primary.sectionTitle}.`,
      `Apply the teaching points for ${input.targetAudience}.`,
      `Connect selected source sections into a coherent learning path.`,
    ];

    if (input.difficultyLevel === "advanced") {
      learningOutcomes.push(
        "Critique and adapt the source ideas for advanced learners.",
      );
    }

    const quizSuggestions = input.sections.slice(0, 5).map((section) => {
      const snippet = firstSentence(
        section.extractedText,
        section.sectionTitle,
      );
      return `Based on ${section.sectionTitle}: what is the main idea behind “${snippet.slice(0, 80)}”?`;
    });

    const outline = {
      title: `${primary.sectionTitle} Course`,
      description: [
        `A ${input.difficultyLevel} course for ${input.targetAudience}.`,
        `Objective: ${input.courseObjective}.`,
        `Duration focus: ${input.durationLabel}.`,
        `Content is structured only from the ${input.sections.length} selected source section(s).`,
      ].join(" "),
      targetAudience: input.targetAudience,
      learningOutcomes,
      modules,
      quizSuggestions,
      sourceReferences: allRefs,
      groundingNotes: [
        "Generated by the mock AI provider using only selected source sections.",
        "No external facts were added beyond the creator inputs and source text.",
      ],
    };

    return courseOutlineSchema.parse(outline);
  }
}
