#!/usr/bin/env bash
# Concatenate migrations + policies in APPLY_ORDER into one SQL file for Supabase.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ORDER_FILE="$ROOT/database/APPLY_ORDER.md"
OUT_DIR="$ROOT/database/dist"
OUT_FILE="$OUT_DIR/supabase_schema.sql"

mkdir -p "$OUT_DIR"

{
  echo "-- Luminary AI — bundled schema"
  echo "-- Generated by scripts/bundle-sql.sh"
  echo "-- Source order: database/APPLY_ORDER.md"
  echo "-- Do not edit by hand; regenerate after SQL changes."
  echo
} > "$OUT_FILE"

mapfile -t REL_PATHS < <(grep -E '^[0-9]+\. `' "$ORDER_FILE" | sed -E 's/^[0-9]+\. `//; s/`$//')

if [[ "${#REL_PATHS[@]}" -eq 0 ]]; then
  echo "No SQL paths found in $ORDER_FILE" >&2
  exit 1
fi

for rel in "${REL_PATHS[@]}"; do
  file="$ROOT/database/$rel"
  if [[ ! -f "$file" ]]; then
    echo "Missing SQL file: $file" >&2
    exit 1
  fi
  {
    echo
    echo "-- ============================================================================="
    echo "-- $rel"
    echo "-- ============================================================================="
    echo
    cat "$file"
    echo
  } >> "$OUT_FILE"
done

echo "Wrote $OUT_FILE (${#REL_PATHS[@]} SQL files bundled)."
